### ISSUE TITLE
Port the package to NPM repository

### ISSUE THREAD

**Issue by Nargonath** [guiassemany/angular-reverse-geocode#1]
I'm using npm as my package manager and not Bower but I cannot load it from NPM. Would it be possible to make a version for NPM as well please?

**Comment by guiassemany** [comment]
Hello @Nargonath, unfortunately I have no time to create it now. I will try to do it in the next few weeks.

**Comment by Nargonath** [comment]
Hello @guiassemany. Thanks for your answer. Looking forward to it. ;)

**Comment by guiassemany** [comment]
@Nargonath I decided to do it because It would be quick 😄 . 
Can you test it? I dont know if that is what you really need!

**Comment by Nargonath** [comment]
@guiassemany Good job, thanks. I don't have the time to test it right now but I should soon and let you know. ;)

**Comment by guiassemany** [comment]
@Nargonat, have you tested it?

**Comment by Nargonath** [comment]
@guiassemany Sorry I forgot about it ... Had been jumping from projects to projects lately and had my mind elsewhere. I'll put it in my todo list and I'll let you know once it has been tested. Thanks again.

**Comment by Nargonath** [comment]
Alright. I just tested it and I made it work but there are some little things to tweak. I'll make a PR.

**Comment by guiassemany** [comment]
Merged! Thank You!

**Comment by Nargonath** [comment]
You are welcome. ;)
